builds:
  - id: &build_id_ssh_inscribe ssh-inscribe
    main: .
    binary: ssh-inscribe
    ldflags:
      - -X github.com/aakso/ssh-inscribe/pkg/globals.version={{ .Version }}
      - -X github.com/aakso/ssh-inscribe/pkg/globals.confDir=/etc/ssh-inscribe
      - -X github.com/aakso/ssh-inscribe/pkg/globals.varDir=/var/lib/ssh-inscribe
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    ignore:
      - goos: linux
        goarch: arm64
  - id: &build_id_sshi sshi
    main: ./cliclient/sshi
    binary: sshi
    ldflags:
      - -X github.com/aakso/ssh-inscribe/pkg/globals.version={{ .Version }}
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
archives:
  - format: binary
    name_template: >-
      {{ .Binary }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
nfpms:
  - id: ssh-inscribe
    package_name: ssh-inscribe
    file_name_template: "{{ .ConventionalFileName }}"
    builds: [*build_id_ssh_inscribe]
    vendor: &vendor Anton Aksola
    homepage: &homepage https://github.com/aakso/ssh-inscribe
    maintainer: &maintainer Anton Aksola <aakso@iki.fi>
    license: &license Apache-2.0
    formats: &formats [rpm]
    contents:
      - src: etc/ssh-inscribe.service
        dst: /usr/lib/systemd/system/ssh-inscribe.service
    scripts:
      preinstall: etc/server-pre-install.sh
      postinstall: etc/server-post-install.sh
  - id: sshi
    package_name: sshi
    file_name_template: "{{ .ConventionalFileName }}"
    builds: [*build_id_sshi]
    vendor: *vendor
    homepage: *homepage
    maintainer: *maintainer
    license: *license
    formats: *formats
checksum:
  name_template: checksums.txt
