name: Release

on:
  pull_request:
  push:
    branches: [master]
    tags: ["*.*.*"]

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: |
          make dist GORELEASER_ARGS="${{ !startsWith(github.ref, 'refs/tags/') && '--snapshot' || '' }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate artifact attestations
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/attest@v4
        with:
          subject-checksums: dist/checksums.txt
        id: attest
      - name: Upload Sigstore bundle
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cp "${ATTEST_BUNDLE_PATH}" artifact-attestation.sigstore.json
          gh release upload "$(jq -r .tag <dist/metadata.json)" artifact-attestation.sigstore.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ATTEST_BUNDLE_PATH: ${{ steps.attest.outputs.bundle-path }}
      - name: Upload to Packagecloud
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          gem install --no-document --user-install --bindir ~/.local/bin package_cloud
          export CLICOLOR_FORCE=1
          ~/.local/bin/package_cloud push ${{ github.repository }}/any/any dist/*.deb
          ~/.local/bin/package_cloud push ${{ github.repository }}/rpm_any/rpm_any dist/*.rpm
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
